# Generated by Django 2.0.4 on 2018-04-28 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_individualuser_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='individualuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='name',
        ),
        migrations.AddField(
            model_name='individualuser',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualuser',
            name='gravatar',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualuser',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='status',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='gravatar',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='organizationuser',
            name='status',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organizationuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
