# Generated by Django 2.0.4 on 2018-04-28 09:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20180428_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(max_length=45)),
                ('gravatar', models.CharField(max_length=200)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('is_trainer', models.BooleanField(default=False)),
                ('is_student', models.BooleanField()),
                ('education', django.contrib.postgres.fields.jsonb.JSONField()),
                ('experience', django.contrib.postgres.fields.jsonb.JSONField()),
                ('experience_years', models.IntegerField(default=0, help_text='experience in months')),
                ('current_organization', models.TextField()),
                ('official_contact', models.CharField(max_length=13)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='individualuser',
            name='auth',
        ),
        migrations.DeleteModel(
            name='IndividualUser',
        ),
    ]
