# Generated by Django 2.0.4 on 2018-04-28 10:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20180428_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address', models.TextField()),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('gravatar', models.CharField(blank=True, max_length=200, null=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_training_institute', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='organizationuser',
            name='auth',
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='current_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='education',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='experience',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='gravatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='status',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationUser',
        ),
    ]
