# Generated by Django 2.0.4 on 2018-04-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180428_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='additional_contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='company_size',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='founded_on',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='industry_type',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
